"
No class-specific documentation for RsrDecoderTest, hierarchy is:
Object
  TestAsserter
    TestCase( testSelector)
      RsrTestCase
        RsrCodecTest( registry decoder)
          RsrDecoderTest

"
Class {
	#name : 'RsrProtocolDecoderV2Test',
	#superclass : 'RsrProtocolDecoderTest',
	#category : 'RemoteServiceReplication-Test',
	#package : 'RemoteServiceReplication-Test'
}

{ #category : 'accessing' }
RsrProtocolDecoderV2Test >> protocolVersion [

	^2
]
